-- MySQL Script generated by MySQL Workbench
-- Tue Apr 17 17:04:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nargilemag
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nargilemag` ;

-- -----------------------------------------------------
-- Schema nargilemag
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nargilemag` DEFAULT CHARACTER SET utf8 ;
USE `nargilemag` ;

-- -----------------------------------------------------
-- Table `nargilemag`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nargilemag`.`users` ;

CREATE TABLE IF NOT EXISTS `nargilemag`.`users` (
  `id` INT(50) UNSIGNED NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  `phone_number` VARCHAR(10) NULL,
  `is_admin` TINYINT NOT NULL,
  `sex` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `nargilemag`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nargilemag`.`categories` ;

CREATE TABLE IF NOT EXISTS `nargilemag`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `categories_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categories_categories1_idx` (`categories_id` ASC),
  CONSTRAINT `fk_categories_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `nargilemag`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `nargilemag`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nargilemag`.`products` ;

CREATE TABLE IF NOT EXISTS `nargilemag`.`products` (
  `id` INT(50) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(350) NULL,
  `price` DOUBLE UNSIGNED NOT NULL,
  `ammount_in_stock` INT(10) NOT NULL,
  `category_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `category_id`),
  INDEX `fk_product_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `nargilemag`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `nargilemag`.`favorite_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nargilemag`.`favorite_products` ;

CREATE TABLE IF NOT EXISTS `nargilemag`.`favorite_products` (
  `users_id` INT(50) UNSIGNED NOT NULL,
  `product_id` INT(50) NOT NULL,
  PRIMARY KEY (`users_id`, `product_id`),
  INDEX `fk_users_has_product_product1_idx` (`product_id` ASC),
  INDEX `fk_users_has_product_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_product_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `nargilemag`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `nargilemag`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `nargilemag`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nargilemag`.`orders` ;

CREATE TABLE IF NOT EXISTS `nargilemag`.`orders` (
  `id` INT(50) NOT NULL AUTO_INCREMENT,
  `date_of_issue` DATE NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone_number` VARCHAR(10) NOT NULL,
  `users_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `nargilemag`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `nargilemag`.`orders_has_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nargilemag`.`orders_has_products` ;

CREATE TABLE IF NOT EXISTS `nargilemag`.`orders_has_products` (
  `orders_id` INT(50) NOT NULL,
  `products_id` INT(50) NOT NULL,
  PRIMARY KEY (`orders_id`, `products_id`),
  INDEX `fk_orders_has_products_products1_idx` (`products_id` ASC),
  INDEX `fk_orders_has_products_orders1_idx` (`orders_id` ASC),
  CONSTRAINT `fk_orders_has_products_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `nargilemag`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `nargilemag`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `nargilemag`.`characteristics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nargilemag`.`characteristics` ;

CREATE TABLE IF NOT EXISTS `nargilemag`.`characteristics` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `unit` INT(10) NULL,
  `categories_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `categories_id`),
  INDEX `fk_characteristics_categories1_idx` (`categories_id` ASC),
  CONSTRAINT `fk_characteristics_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `nargilemag`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `nargilemag`.`products_have_characteristics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nargilemag`.`products_have_characteristics` ;

CREATE TABLE IF NOT EXISTS `nargilemag`.`products_have_characteristics` (
  `products_id` INT(50) NOT NULL,
  `characteristics_id` INT(10) NOT NULL,
  `value` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`products_id`, `characteristics_id`),
  INDEX `fk_products_has_characteristics_characteristics1_idx` (`characteristics_id` ASC),
  INDEX `fk_products_has_characteristics_products1_idx` (`products_id` ASC),
  CONSTRAINT `fk_products_has_characteristics_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `nargilemag`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_characteristics_characteristics1`
    FOREIGN KEY (`characteristics_id`)
    REFERENCES `nargilemag`.`characteristics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `nargilemag`.`product_ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nargilemag`.`product_ratings` ;

CREATE TABLE IF NOT EXISTS `nargilemag`.`product_ratings` (
  `users_id` INT(50) UNSIGNED NOT NULL,
  `products_id` INT(50) NOT NULL,
  `rating` INT(1) NOT NULL,
  PRIMARY KEY (`users_id`, `products_id`),
  INDEX `fk_users_has_products_products1_idx` (`products_id` ASC),
  INDEX `fk_users_has_products_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_products_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `nargilemag`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `nargilemag`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
